---
--- Generated by Luanalysis
--- Created by bonington.
--- DateTime: 2022/10/23 17:17
---
workspace "Funtal"
    architecture "x86_64"

    configuration
    {
        "Debug",
        "Release",
        "Dist"
    }

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "Funtal"
    location "Funtal"
    kind "SharedLib"
    language "C++"

    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("object/" .. outputdir .. "/%{prj.name}")

    files
    {
        "%{proj.name}/src/**.h",
        "%{proj.name}/src/**.cpp"
    }

    include
    {
        "%{proj.name}/vendor/spdlog/include"
    }

    filter "system:macos"
        cppdialect "C++23"
        staticruntime "On"
        systemversion "latest"

        defines
        {
            "FT_PLATFORM_MACOS",
            "FT_BUILD_DLL"
        }

        postbuildcommands
        {
            ("{COPY} %{cfg.buildtarget.relpath} ../lib/")
        }

    filter "configuration:Debug"
        defines "FT_DEBUG"
        symbols "On"

    filter "configuration:Dist"
        defines "FT_DIST"
        optimize "On"


project "Sandbox"
    location "Sandbox"
    kind "ConsoleApp"
    language "C++"

    targetdir ("bin/" .. outputdir .. "/%{prj.name}")
    objdir ("object/" .. outputdir .. "/%{prj.name}")

    files
    {
        "%{proj.name}/src/**.h",
        "%{proj.name}/src/**.cpp"
    }

    includedirs
    {
        "%{prj.name}/src",
        "%{proj.name}/vendor/spdlog/include",
        "Funtal/src"
    }

    links
    {
        "Funtal"
    }

    filter "system:macos"
        cppdialect "C++23"
        staticruntime "On"
        systemversion "latest"

    defines
    {
        "FT_PLATFORM_MACOS"
    }

    filter "configuration:Debug"
        defines "FT_DEBUG"
        symbols "On"

    filter "configuration:Dist"
        defines "FT_DIST"
        optimize "On"
